### ISSUE TITLE
Rewards Dashboard and Token Calculator

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/astral#344]
With the release of the incentivized testnet, the block explorer must allow users to view their earned rewards. Also, allow them to view based on all their previous and future rewards how many tokens they will have on mainnet launch.  

[Figma design](https://www.figma.com/file/nRWatk3fZ3Rg2SYjbRLaIu/Subspace---Block-Explorer?type=design&node-id=2901-2&mode=design&t=9bxkSp4GsTZvEYhN-0)

```[tasklist]
### Backend tasks
- [ ] https://github.com/subspace/astral/issues/361
- [ ] https://github.com/subspace/astral/issues/376
```

```[tasklist]
### Frontend tasks
- [x] https://github.com/subspace/astral/issues/362
- [ ] https://github.com/subspace/astral/issues/384
- [ ] https://github.com/subspace/astral/issues/385
```
