### ISSUE TITLE
Frontend Bugs and Styles issues to address

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/astral#387]
```[tasklist]
### Frontend bugs and style Issues
- [ ] https://github.com/subspace/astral/issues/380
- [ ] https://github.com/subspace/astral/issues/388
- [ ] https://github.com/subspace/astral/issues/393
- [ ] https://github.com/subspace/astral/issues/389
- [ ] https://github.com/subspace/astral/issues/390
- [ ] https://github.com/subspace/astral/issues/391
- [ ] https://github.com/subspace/astral/issues/392
- [ ] https://github.com/subspace/astral/issues/410
```
