### ISSUE TITLE
Prep for gemini 3h

### ISSUE THREAD

**Issue by DianaPertseva** [subspace/astral#426]
Gemini 3h Roll-out checklist https://www.notion.so/subspacelabs/Gemini-3h-c2208b6fb02240bdada8fb3824ebbb92 
```[tasklist]
### Tasks
- [ ] https://github.com/subspace/astral/issues/475
- [ ] https://github.com/subspace/astral/issues/476
- [ ] https://github.com/subspace/astral/issues/477
```
