### ISSUE TITLE
A list of small-ish Astral issues

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/astral#706]
Credits for creating this issue list based on personal and user's feedback go to @randywessels 
 
```[tasklist]
### Tasks
- [] Disable sorting on “Manage my nomination” as it crashes the page
- [] Last extrinsics on pop-out is blank 
- [] New extrinsics on pop-out seems to be stuck in pending forever 
- [] Your total staked seem to match "Your total staked" in your own operators - both by a massively overstaked amount for me. This is in the summary table under the grid.
- [] Pop-out can flicker as it moves up and down vertically - although this seems to happen a bit less.
- [] Filter on Extrinsics page doesn’t do anything. https://explorer.subspace.network/gemini-3h/consensus/extrinsics
- [] When drilling into an operator for detail, most of the records in the Stakes column have a value of zero. The Stakes column is incorrect for my operator #30.
- [] Operators that are no longer registered and have no funds allocated are still showing a total stake amount. Example operator id’s 13 and 14. 14 also still shows nominators.
- [] On both the Manage My Operator and Manage My Nomination tabs the grid says Page 1 of 0.
- [] On Manage My Nomination Tab, the option to Nominate a deregistered operator should be removed.
- [] On the operators tab you can still select Nominate on a Slashed Operator.
- [] On the operators tab the signing key columns for your operators is misaligned.
```

Please tag me or Randy if any of the issues is unclear.
