### ISSUE TITLE
Add a way to query most staking details from RPC

### ISSUE THREAD

**Issue by marc-aurele-besner** [subspace/astral#741]
## Add a way to query most staking details from RPC

```[tasklist]
### Tasks
- [ ] #729
- [ ] https://github.com/subspace/astral/issues/742
- [ ] https://github.com/subspace/astral/issues/743
- [ ] https://github.com/subspace/astral/issues/747
- [ ] https://github.com/subspace/astral/issues/748
```
